---
- name: Create and start dozzle container
  community.docker.docker_container:
    name: dozzle
    image: "{{ dozzle_image }}"
    pull: true
    recreate: true
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - name: monitoring
    labels:
      org.label-schema.group: monitoring
  tags:
    - setup
    - update
    - setup-dozzle
    - update-dozzle

- name: Update caddy config
  ansible.builtin.template:
    src: dozzle.j2
    dest: /srv/caddy/sites/dozzle
    mode: "0644"
  notify: Restart caddy
  tags:
    - setup
    - update
    - setup-dozzle
    - update-dozzle
