---
- name: Create anonymousoverflow directory
  ansible.builtin.file:
    path: /opt/anonymousoverflow
    state: directory
    mode: "0755"
  tags:
    - setup

- name: Setup anonymousoverflow
  ansible.builtin.template:
    src: compose.yml.j2
    dest: /opt/anonymousoverflow/compose.yml
    mode: "0644"
  notify: Restart anonymousoverflow
  tags:
    - setup
    - update

- name: Update caddy config
  ansible.builtin.template:
    src: overflow.j2
    dest: /srv/caddy/sites/overflow
    mode: "0644"
  notify: Restart caddy
  tags:
    - setup
    - update
