---
- name: Create anonymousoverflow directory
  ansible.builtin.file:
    path: /opt/anonymousoverflow
    state: directory
    mode: "0755"

- name: Setup anonymousoverflow
  ansible.builtin.template:
    src: compose.yml.j2
    dest: /opt/anonymousoverflow/compose.yml
    mode: "0644"
  notify: restart anonymousoverflow

- name: Update caddy config
  ansible.builtin.template:
    src: overflow.j2
    dest: /srv/caddy/sites/overflow
    mode: "0644"
  notify: restart caddy
