---
services_domain: tmak2002.dev
searxng_instance_name: SearXNG@tmak2002.dev
searxng_privacypolicy_url: https://tmak2002.dev
searxng_donation_url: https://tmak2002.dev/donate
searxng_contact_url: https://tmak2002.dev
linkding_domain: tmak2002.de
