---
- name: Create netdata data directory
  ansible.builtin.file:
    path: /srv/netdata
    state: directory
    mode: "0755"
  tags:
    - setup

- name: Create and start netdata container
  community.docker.docker_container:
    name: netdata
    image: "{{ netdata_image }}"
    pull: true
    recreate: true
    restart_policy: unless-stopped
    pid_mode: host
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /srv/netdata/config:/etc/netdata
      - /srv/netdata/lib:/var/lib/netdata 
      - /srv/netdata/cache:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    capabilities:
      - SYS_PTRACE
      - SYS_ADMIN
    cap_drop:
        - ALL
    networks:
      - name: monitoring
    labels:
      org.label-schema.group: monitoring
  tags:
    - setup
    - update

- name: Update caddy config
  ansible.builtin.template:
    src: netdata.j2
    dest: /srv/caddy/sites/netdata
    mode: "0644"
  notify: Restart caddy
  tags:
    - setup
    - update
