---
- name: Deploy redlib
  community.docker.docker_container:
    name: redlib
    image: quay.io/redlib/redlib@sha256:8c6c56472380188edc8dcd15b1a8e6741281635446b95c6ef1222f9940a96d93
    pull: true
    recreate: true
    restart_policy: unless-stopped
    user: nobody
    read_only: true
    cap_drop:
      - ALL
    networks:
      - name: core
    security_opts:
      - no-new-privileges:true
    healthcheck:
      test: [CMD, wget, --spider, -q, --tries=1, http://localhost:8080/settings]
      interval: 5m
      timeout: 3s
    labels: traefik.enable=true traefik.http.routers.redlib.rule=Host(`redlib.{{ domain }}`) traefik.http.routers.redlib.entrypoints=websecure traefik.http.routers.redlib.tls.certresolver=letsencrypt
      traefik.http.services.redlib.loadbalancer.server.port=8080
  tags:
    - setup
    - update
