---
- name: Create ddclient data directory
  ansible.builtin.file:
    path: /srv/ddclient
    state: directory
    mode: "0755"
  tags:
    - setup

- name: Setup ddclient.conf
  ansible.builtin.template:
    src: ddclient.conf.j2
    dest: /srv/ddclient/ddclient.conf
    mode: "0644"
  tags:
    - setup
    - update

- name: Setup ddclient
  community.docker.docker_container:
    name: ddclient
    image: "{{ ddclient_image }}"
    pull: true
    recreate: true
    restart_policy: unless-stopped
    volumes:
      - /srv/ddclient/ddclient.conf:/config/ddclient.conf
  tags:
    - setup
    - update
