---
- name: Create core network
  community.docker.docker_network:
    name: core
  tags:
    - setup

- name: Create services network
  community.docker.docker_network:
    name: services
  tags:
    - setup

- name: Create tools network
  community.docker.docker_network:
    name: tools
  tags:
    - setup

- name: Create monitoring network
  community.docker.docker_network:
    name: monitoring
  tags:
    - setup
