---
- name: Create homepage directory
  ansible.builtin.file:
    path: /srv/homepage
    state: directory
    mode: "0755"
  tags:
    - setup

- name: Deploy homepage
  community.docker.docker_container:
    name: homepage
    image: ghcr.io/gethomepage/homepage:v1.2.0
    pull: true
    recreate: true
    restart_policy: unless-stopped
    volumes:
      - /srv/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env:
      HOMEPAGE_ALLOWED_HOSTS: home.tmak2002.de
    networks:
      - name: core
    labels: traefik.enable=true traefik.http.routers.homepage.rule=Host(`home.{{ domain }}`) traefik.http.routers.homepage.entrypoints=websecure traefik.http.routers.homepage.tls.certresolver=letsencrypt
      traefik.http.services.hompage.loadbalancer.server.port=3000
  tags:
    - setup
    - update
