---
- name: Create sftpgo data directory
  ansible.builtin.file:
    path: /srv/sftpgo
    state: directory
    mode: "0755"
  tags:
    - setup

- name: Create and start sftpgo container
  community.docker.docker_container:
    name: sftpgo
    image: "{{ sftpgo_image }}"
    pull: true
    recreate: true
    restart_policy: unless-stopped
    ports:
      - 21:21/tcp
      - 21000-21010:21000-21010/tcp
    volumes:
      - /srv/ftp:/srv/sftpgo/data
      - /srv/sftpgo/backups:/srv/sftpgo/backups
      - /srv/sftpgo/home:/var/lib/sftpgo
    env:
      SFTPGO_FTPD__BINDINGS__0__PORT: "21"
      SFTPGO_FTPD__PASSIVE_PORT_RANGE__START: "21000"
      SFTPGO_FTPD__PASSIVE_PORT_RANGE__END: "21010"
    networks:
      - name: core
  tags:
    - setup
    - update

- name: Update caddy config
  ansible.builtin.template:
    src: sftpgo.j2
    dest: /srv/caddy/sites/sftpgo
    mode: "0644"
  notify: Restart caddy
  tags:
    - setup
    - update
