---
- name: Create uptime-kuma data directory
  ansible.builtin.file:
    path: /srv/uptime-kuma
    state: directory
    mode: "0755"
  tags:
    - setup

- name: Create and start uptime-kuma container
  community.docker.docker_container:
    name: uptime-kuma
    image: "{{ uptime_kuma_image }}"
    pull: true
    recreate: true
    restart_policy: unless-stopped
    volumes:
      - /srv/uptime-kuma/data:/app/data
    networks:
      - name: monitoring
    labels:
      org.label-schema.group: "monitoring"
  tags:
    - setup
    - update

- name: Update caddy config
  ansible.builtin.template:
    src: uptime-kuma.j2
    dest: /srv/caddy/sites/uptime-kuma
    mode: "0644"
  notify: Restart caddy
  tags:
    - setup
    - update
