---
- name: Restart portainer
  ansible.builtin.command:
    chdir: /opt/portainer
    cmd: "{{ docker_update_command }}"

- name: Restart caddy
  ansible.builtin.command:
    cmd: "{{ caddy_restart_command }}"
