---
- name: Set up FangDasKissenDev
  hosts: FangDasKissenDev
  become: true

  roles:
    - caddy
    - sftpgo
    - pihole
    - uptime_kuma
    - searxng
    - redlib
    - anonymousoverflow
    - proxitok
