---
- name: Create authelia data directory
  ansible.builtin.file:
    path: /srv/authelia
    state: directory
    mode: "0755"
  tags:
    - setup
    - setup-authelia

- name: Setup configuration
  ansible.builtin.template:
    src: configuration.yml.j2
    dest: /srv/authelia/configuration.yml
    mode: "0644"
  tags:
    - setup
    - update
    - setup-authelia
    - update-authelia

- name: Setup users_database
  ansible.builtin.template:
    src: users_database.yml.j2
    dest: /srv/authelia/users_database.yml
    mode: "0644"
  tags:
    - setup
    - update
    - setup-authelia
    - update-authelia

- name: Create and start authelia container
  community.docker.docker_container:
    name: authelia
    image: "{{ authelia_image }}"
    pull: true
    recreate: true
    restart_policy: unless-stopped
    volumes:
      - /srv/authelia:/config
    env:
      TZ: "{{ timezone }}"
    networks:
      - name: core
  tags:
    - setup
    - update
    - setup-authelia
    - update-authelia

- name: Update caddy config
  ansible.builtin.template:
    src: authelia.j2
    dest: /srv/caddy/sites/authelia
    mode: "0644"
  notify: Restart caddy
  tags:
    - setup
    - update
    - setup-authelia
    - update-authelia
