---
services_domain: internal
searxng_instance_name: SearXNG@tmak2002.dev
searxng_privacypolicy_url: https://tmak2002.dev
searxng_donation_url: https://tmak2002.dev/donate
searxng_contact_url: https://tmak2002.dev
anonymousoverflow_secret: ieTae4ahzoophohxo4la
searxng_secret: osaeloozox4thiebai8M
pihole_password: EiVeek2ishaif0dohtho
ftp_users: test|pohfahha1hah1SeimieJ
