---
- name: Create traefik directorys
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /opt/traefik
    - /srv/traefik
  tags:
    - setup
    - setup-traefik

- name: Copy compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: /opt/traefik/compose.yml
    mode: "0644"
  tags:
    - setup
    - setup-traefik
    - update
    - update-traefik

- name: Start traefik
  community.docker.docker_compose_v2:
    project_src: /opt/traefik/
    state: present
    pull: always
    recreate: always
  tags:
    - setup
    - setup-traefik
    - update
    - update-traefik
