---
- name: Create proxitok network
  community.docker.docker_network:
    name: proxitok
    state: present
  tags:
    - setup

- name: Deploy proxitok signer
  community.docker.docker_container:
    name: proxitok-signer
    image: ghcr.io/pablouser1/signtok:latest@sha256:c55ed70b17ebd4a237c2bbbea71579c4800c89ad4c15a1e6e2060006378a353f
    pull: true
    recreate: true
    restart_policy: unless-stopped
    user: nobody
    read_only: true
    security_opts:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - name: proxitok
  tags:
    - setup
    - update

- name: Deploy valkey
  community.docker.docker_container:
    name: proxitok-valkey
    image: valkey/valkey:8.1.1-alpine
    pull: true
    recreate: true
    command: valkey-server --save 60 1 --loglevel warning
    restart_policy: unless-stopped
    user: nobody
    read_only: true
    security_opts:
      - no-new-privileges:true
    tmpfs:
      - /data:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev
    cap_drop:
      - ALL
    networks:
      - name: proxitok
  tags:
    - setup
    - update

- name: Deploy proxitok
  community.docker.docker_container:
    name: proxitok
    image: ghcr.io/pablouser1/proxitok:latest@sha256:53537d2c9f816c313a13f232d728175e1932d9d59145ffc33f26387d81c69fc6
    pull: true
    recreate: true
    restart_policy: unless-stopped
    env:
      LATTE_CACHE: /cache
      API_CACHE: redis
      REDIS_HOST: proxitok-valkey
      REDIS_PORT: "6379"
      API_SIGNER: remote
      API_SIGNER_URL: http://proxitok-signer:8080/signature
    security_opts:
      - no-new-privileges:true
    cap_drop:
      - ALL
    capabilities:
      - CHOWN
      - SETGID
      - SETUID
    networks:
      - name: core
      - name: proxitok
    labels: traefik.enable=true traefik.http.routers.proxitok.rule=Host(`proxitok.{{ domain }}`) traefik.http.routers.proxitok.entrypoints=websecure traefik.http.routers.proxitok.tls.certresolver=letsencrypt
      traefik.http.services.proxitok.loadbalancer.server.port=8080
  tags:
    - setup
    - update
