---
- name: Create anonymousoverflow directorys
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /opt/anonymousoverflow
  tags:
    - setup
    - setup-anonymousoverflow

- name: Copy compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: /opt/anonymousoverflow/compose.yml
    mode: "0644"
  tags:
    - setup
    - setup-anonymousoverflow
    - update
    - update-anonymousoverflow

- name: Start anonymousoverflow
  community.docker.docker_compose_v2:
    project_src: /opt/anonymousoverflow/
    state: present
    pull: always
    recreate: always
  tags:
    - setup
    - setup-anonymousoverflow
    - update
    - update-anonymousoverflow
