---
- name: Create komga config directory
  ansible.builtin.file:
    path: /srv/komga
    state: directory
    owner: 1000
    group: 1000
    mode: "0755"
  tags:
    - setup
    - setup-komga

- name: Create komga data directory
  ansible.builtin.file:
    path: "{{ komga_data_dir }}"
    state: directory
    owner: 1000
    group: 1000
    mode: "0755"
  tags:
    - setup
    - setup-komga

- name: Setup komga
  community.docker.docker_container:
    name: komga
    image: "{{ komga_image }}"
    pull: true
    recreate: true
    user: 1000:1000
    restart_policy: unless-stopped
    volumes:
      - /srv/komga:/config:rw
      - "{{ komga_data_dir }}:/data:rw"
      - /etc/timezone:/etc/timezone:ro
    networks:
      - name: tools
  tags:
    - setup
    - update
    - setup-komga
    - update-komga

- name: Update caddy config
  ansible.builtin.template:
    src: komga.j2
    dest: /srv/caddy/sites/komga
    mode: "0644"
  notify: Restart caddy
  tags:
    - setup
    - update
    - setup-komga
    - update-komga
