---
- name: Create komga directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: 1000
    group: 1000
  loop:
    - /srv/komga
    - /srv/komga/config
    - /srv/komga/data
  tags:
    - setup

- name: Deploy komga
  community.docker.docker_container:
    name: komga
    image: gotson/komga:1.23.5
    pull: true
    recreate: true
    restart_policy: unless-stopped
    user: "1000:1000"
    volumes:
      - /srv/komga/config:/config
      - /srv/komga/data:/data
    env:
      TZ: "{{ timezone }}"
    networks:
      - name: core
    labels: traefik.enable=true traefik.http.routers.komga.rule=Host(`komga.{{ domain }}`) traefik.http.routers.komga.entrypoints=websecure
      traefik.http.routers.komga.tls.certresolver=letsencrypt traefik.http.services.komga.loadbalancer.server.port=25600
  tags:
    - setup
    - update
