---
- name: Create pihole & unbound directorys
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /opt/pihole
    - /srv/unbound
    - /srv/pihole
  tags:
    - setup
    - setup-dns

- name: Copy unbound unbound.conf
  ansible.builtin.template:
    src: unbound.conf.j2
    dest: /srv/unbound/unbound.conf
    mode: "0644"
  tags:
    - setup
    - update
    - setup-pihole
    - update-pihole

- name: Copy compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: /opt/pihole/compose.yml
    mode: "0644"
  tags:
    - setup
    - update
    - setup-pihole
    - update-pihole

- name: Start pihole & unbound
  community.docker.docker_compose_v2:
    project_src: /opt/pihole
    state: present
    pull: always
    recreate: always
  tags:
    - setup
    - update
    - setup-pihole
    - update-pihole
