---
- name: Deploy cloudflared
  community.docker.docker_container:
    name: cloudflared
    image: cloudflare/cloudflared:2025.9.1
    pull: true
    recreate: true
    restart_policy: unless-stopped
    command: tunnel run
    env: TUNNEL_TOKEN={{ cloudflared_token }}
    networks:
      - name: core
  tags:
    - setup
    - update
