---
- name: Create cloudflared directorys
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "/opt/cloudflared"
  tags:
    - setup 
    - setup-cloudflared

- name: Copy compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "/opt/cloudflared/compose.yml"
    mode: "0644"
  tags:
    - setup
    - setup-cloudflared
    - update
    - update-cloudflared

- name: Start cloudflared
  community.docker.docker_compose_v2:
    project_src: "/opt/cloudflared/"
    state: present
    pull: always
    recreate: always
  tags:
    - setup
    - setup-cloudflared
    - update
    - update-cloudflared
